### ISSUE TITLE
Undefined array key 1 {"file":"Message.php","line":174} 

### ISSUE THREAD

**Issue by marcin-lawrowski** [opcodesio/mail-parser#1]
Hello

It looks it fails on headers like this one:

ARC-Seal: i=1; a=rsa-sha256; t=1731423677; cv=none;
        d=google.com; s=arc-20240605;
        b=HWyeknBTKrwZQ4qfvrr/EOGaEDVxwAyAT9bNP2FRlQOXW/pkf8cy0wsRwswG0LzJWX
         pGPOZfBLUGr2XFwuvg5/k9uxamiYe5hIHGtcSrUpq6gatYyBBqMh2eLikBf1mWLK1EPU
         7YbBYQ7Gxcigx6hEZxnEcpXTvhEfNskuF81UxoMfTfoqWRMXKaAb8r5SNOs50E5G4ZIQ
         lUqqxjvfaJS/C4UdnxOzlSs02DTaFiruj7ZPxnPe35G6JoeT7KW+Z1VofLf3ZBFoY2f9
         cIOZoYSzKuquOnqChKRDyW+29iD2QyO6htwn7iPwRvvJnn7CGhb/l6yEPtyINlgX/OP5
         8b+g==

I think line 175 in Message.php is totally wrong:
$headerInProgress = str_ends_with($this->headers[$headerInProgress], ';');

It sets "1" to $headerInProgress variable (the result of str_ends_with function). Maybe this header is not fully compatible with RFC, but the library should be immune to wrong headers because the rest of them may be 100% correct. I tested this library on 4 random EML files and it failed on 2 of them. 

Best regards
Marcin

**Comment by arukompas** [comment]
@marcin-lawrowski hey Marcin, thanks for the report! Would you mind sharing the full **failing** EML file here? If it's test data, or anonymised. I'll the case to the test suite and find a solution.

**Comment by marcin-lawrowski** [comment]
[Erpix Karcher Center2024-11-12 1601.zip](https://github.com/user-attachments/files/18026539/Erpix.Karcher.Center2024-11-12.1601.zip)

**Comment by marcin-lawrowski** [comment]
Here is EML file I tested this library with. I anonymised few things, but it should behave the same. Thank you.

**Comment by arukompas** [comment]
Hey @marcin-lawrowski , this should now be fixed in **v0.2.0**. Be sure to update the package with `composer update opcodesio/mail-parser`

Let me know if you're still experiencing issues!
